DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS analysis;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT
);

CREATE TABLE analysis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  original_text TEXT NOT NULL,
  stop_word INTEGER NOT NULL,
  top_ten_words TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);